/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application.vue')['default']
    DebugPanel: typeof import('./src/components/DebugPanel.vue')['default']
    Key: typeof import('./src/components/Key.vue')['default']
    KeyboardRender: typeof import('./src/components/KeyboardRender.vue')['default']
    KeyboardTracker: typeof import('./src/components/KeyboardTracker.vue')['default']
    KeymapPanel: typeof import('./src/components/KeymapPanel.vue')['default']
    KeySelector: typeof import('./src/components/KeySelector.vue')['default']
    KleConverter: typeof import('./src/components/KleConverter.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMarquee: typeof import('naive-ui')['NMarquee']
    NMarqueue: typeof import('naive-ui')['NMarqueue']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NThing: typeof import('naive-ui')['NThing']
    PerformancePanel: typeof import('./src/components/PerformancePanel.vue')['default']
    RGBPanel: typeof import('./src/components/RGBPanel.vue')['default']
  }
}
