[package]
name = "keyboard_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
palette = { version = "0.7.6", features = ["serializing"] }
serde = { version = "1.0.215", features = ["derive"] }